name: 🔨 Build scikit-decide doc

on:
  workflow_dispatch:
    inputs:
      release-version:
        type: choice
        description: "Release version to document"
        options:
        - 0.9.2
        - 0.9.3

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      DOCS_VERSION_PATH: /

    steps:
      - run: |
          echo "Building docs for version: ${{ github.event.inputs.release-version }}"
          env | grep GITHUB_

      - name: Update DOCS_VERSION_PATH
        run: |
            echo SK_VERSION=v"${{ github.event.inputs.release-version }}" >> $GITHUB_ENV
            # replace v with nothing in release-version
            echo DOCS_VERSION_PATH=version/"${{ github.event.inputs.release-version }}"/ >> $GITHUB_ENV

      - name: Set env variables for github+binder links in doc
        run: |
          echo "AUTODOC_BINDER_ENV_GH_REPO_NAME=airbus/scikit-decide" >> $GITHUB_ENV
          echo "AUTODOC_BINDER_ENV_GH_BRANCH=binder" >> $GITHUB_ENV
          echo "AUTODOC_NOTEBOOKS_REPO_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          echo "AUTODOC_NOTEBOOKS_BRANCH=${SK_VERSION}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          ref: v${{ github.event.inputs.release-version }}

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install scikit-decide
        run: |
          pip install "scikit-decide[all]==${SK_VERSION/v/}"

      - name: generate documentation
        run: |
          (cd docs && python autodoc.py)
          yarn install && yarn docs:build && touch docs/.vuepress/dist/.nojekyll

      - name: upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: docs/.vuepress/dist

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vuepress/dist # The folder the action should deploy.
          target-folder: ${{ env.DOCS_VERSION_PATH }} # The folder the action should deploy to.
          commit-message: publish documentation
          clean: false # Releasing a new version is about creating a new directory, so we don't want to clean up the root.
